#!/bin/bash
if type "ccache" > /dev/null 2>&1; then
    export CCACHE_SLOPPINESS=pch_defines,time_macros
    exec `which ccache` $DT_TOOLCHAIN_DIR/usr/bin/clang -Xclang -fno-pch-timestamp "$@"
else
    exec $DT_TOOLCHAIN_DIR/usr/bin/clang "$@"
fi